dataset_config:
  stvqa:
    data_dir: ${env.data_dir}/datasets
    depth_first: false
    fast_read: false
    max_features: 100
    use_images: false
    use_features: true
    features:
      train:
      - textvqa/defaults/features/open_images/detectron.lmdb
      val:
      - textvqa/defaults/features/open_images/detectron.lmdb
      test:
      - textvqa/defaults/features/open_images/detectron.lmdb
    annotations:
      train:
      - textvqa/defaults/annotations/ocr_postprocess/rerank_stvqa_train.npy #change
      val:
      - textvqa/defaults/annotations/ocr_postprocess/rerank_stvqa_train.npy #change
      test:
      - textvqa/defaults/annotations/ocr_postprocess/rerank_stvqa_test.npy #change
    processors:
      text_processor:
        type: vocab
        params:
          max_length: 14
          vocab:
            type: intersected
            embedding_name: glove.6B.300d
            vocab_file: stvqa/defaults/extras/vocabs/vocabulary_100k.txt
          preprocessor:
            type: simple_sentence
            params: {}
      answer_processor:
        type: vqa_answer
        params:
          vocab_file: stvqa/defaults/extras/vocabs/fixed_answer_vocab_stvqa_5k.txt
          preprocessor:
            type: simple_word
            params: {}
          num_answers: 10
      context_processor:
        type: fasttext
        params:
          max_length: 50
          model_file: wiki.en.bin
      ocr_token_processor:
        type: simple_word
        params: {}
      bbox_processor:
        type: bbox
        params:
          max_length: 50
    return_features_info: true
    use_ocr: true
    use_ocr_info: false
